const photo = (id: string, width = 1200) => `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${width}&q=85`

export const loveStory = {
  yourName: 'Your Name',
  partnerName: 'thae thae',
  title: 'Our Love Story',
  music: { src: '/music/our-song.mp3', enabled: true, volume: 0.35 },
  dates: {
    firstMeeting: '2024-01-01',
    confession: '2024-02-14',
    anniversary: '2026-01-10',
    birthday: '2000-05-20',
  },
  images: {
    hero: photo('photo-1473116763249-2faaef81ccda', 2000),
    confession: photo('photo-1516589178581-6cd7833ae3b2'),
    valentines: photo('photo-1457089328109-e5d9bd499191'),
    final: photo('photo-1470252649378-9c29740c9fa8', 1800),
  },
  messages: {
    opening: 'Every love story is beautiful...',
    openingReveal: 'But ours is my favorite.',
    openingNote: 'All the little moments. All the big feelings.\nA story I would choose, over and over again.',
    welcomeTitle: 'Hi, my love.',
    welcome: 'Before you came into my life, I never knew that one person could become such an important part of my world.',
    welcomeEnd: 'So I made this little place on the internet...\njust for you.',
    falling: "I don't know exactly when it happened.\n\nMaybe it was one conversation.\nMaybe it was one smile.\nMaybe it was all the little moments we shared.\n\nBut somewhere along the way,\nyou became someone I couldn't stop thinking about.",
    fallingReveal: 'And that is when I realized...\nI had fallen for you.',
    confessionStory: 'I remember the nervousness. The words I rehearsed a hundred times. And the quiet courage it took to let you see my heart.',
    confession: 'I had so many things I wanted to say,\nbut somehow three words were enough...\n\nI love you.\n\nNot just for who you are, but for how much more like myself I feel when I am with you.',
    birthday: 'Happy Birthday to the person who makes my world a little brighter just by being in it.',
    birthdayWish: 'Make a wish, my love.',
    birthdayLetter: 'My love,\n\nToday, I celebrate you. Your kindness, your laughter, and the way you make ordinary days feel like something worth remembering.\n\nI hope this year is gentle with you. I hope it brings you closer to your dreams. And I hope I get to be beside you for all of it.\n\nHere is to you, and all the beautiful things ahead.',
    anniversary: 'Every day with you is another memory I want to keep.',
    valentines: 'Not just today. Not just on the days with flowers.\nI choose you in the small, quiet moments, too.',
    valentinesHidden: 'You do not have to be anything other than yourself to be loved by me. The ordinary days with you are the ones I look forward to most.',
    letter: 'My love,\n\nThere are so many things I want to tell you...\n\nThank you for being part of my life.\nThank you for every smile.\nThank you for every conversation.\nThank you for every memory.\n\nI do not know what the future will look like, but I know that I want to keep creating beautiful memories with you.\n\nI want the quiet mornings, the unexpected adventures, and all the wonderfully ordinary days in between.\n\nWith all my heart,',
    future: 'The best part of our story may still be ahead of us.',
    finalIntro: "After everything we've shared...",
    final: 'Will you stay and create many more memories with me?',
    finalEnd: 'Our next chapter starts here.',
    finalResponse: 'Here is to us. And all the days still to come.',
  },
  timeline: [
    { date: '2024-01-01', title: 'A hello that changed everything', description: 'The first time we met. I had no idea that an ordinary day would become the beginning of my favorite story.', image: photo('photo-1511988617509-a57c8a288659'), icon: 'heart', tag: 'THE FIRST HELLO' },
    { date: '2024-01-05', title: 'Just one more conversation', description: 'We talked about everything and nothing. Somehow, I never wanted the conversation to end.', image: photo('photo-1511081692775-05d0f180a065'), icon: 'message', tag: 'OUR FIRST CONVERSATION' },
    { date: '2024-01-12', title: 'A little moment, a big memory', description: 'A walk, a laugh, a moment that was entirely ours. It is still one of my favorite places to return to in my mind.', image: photo('photo-1473116763249-2faaef81ccda'), icon: 'camera', tag: 'THE FIRST MEMORY' },
    { date: '2024-01-23', title: 'You stayed on my mind', description: 'I started noticing the little things. Your smile. Your kindness. The way my day felt better after hearing from you.', image: photo('photo-1470252649378-9c29740c9fa8'), icon: 'sparkles', tag: 'SOMETHING WAS CHANGING' },
    { date: '2024-02-01', title: 'You became my favorite person', description: 'Somewhere between all those little moments, you stopped being just someone I knew. You became someone I wanted in all my tomorrows.', image: photo('photo-1516589178581-6cd7833ae3b2'), icon: 'heart', tag: 'SOMETHING LIKE LOVE' },
  ],
  memories: [
    { image: photo('photo-1516589178581-6cd7833ae3b2'), date: '2024-03-01', location: 'Just us', caption: 'My favorite place is beside you.', description: 'The beginning of our next chapter. A day that felt like coming home.' },
    { image: photo('photo-1473116763249-2faaef81ccda'), date: '2024-06-15', location: 'By the sea', caption: 'Salt air & stolen moments', description: 'No plans, no hurry. Just the sea, the breeze, and your hand in mine.' },
    { image: photo('photo-1511081692775-05d0f180a065'), date: '2024-08-10', location: 'Our little cafe', caption: 'Coffee tastes better with you.', description: 'One coffee became two. A quick catch-up became an entire afternoon.' },
    { image: photo('photo-1457089328109-e5d9bd499191'), date: '2025-02-14', location: 'A little surprise', caption: 'Flowers, just because.', description: 'A small reminder that you are always on my mind.' },
    { image: photo('photo-1464349095431-e9a21285b5f3'), date: '2025-05-20', location: 'Your special day', caption: 'Another wish, another year.', description: 'Celebrating my favorite person and all the possibilities ahead.' },
    { image: photo('photo-1470252649378-9c29740c9fa8'), date: '2025-09-21', location: 'Somewhere beautiful', caption: 'The days we wish could last.', description: 'We watched the light change and let the world be quiet for a while.' },
  ],
  future: [
    { title: 'More birthdays', text: 'More candles. More wishes. More reasons to celebrate you.', icon: 'cake' },
    { title: 'More anniversaries', text: 'Another year of choosing each other, in a thousand little ways.', icon: 'heart' },
    { title: 'More adventures', text: 'New places, familiar hands, and a world waiting for us.', icon: 'compass' },
    { title: 'More conversations', text: 'Late-night thoughts and stories only we understand.', icon: 'message' },
    { title: 'More memories', text: 'The big milestones and the beautifully ordinary in-between.', icon: 'camera' },
    { title: 'More reasons to smile', text: 'Because life feels a little lighter with you beside me.', icon: 'sun' },
  ],
}